name: Telegram Notification

on:
  repository_dispatch: # Triggers when a repository_dispatch event is sent
    types:
      - api_hit

jobs:
  send-message:
    runs-on: ubuntu-latest

    steps:
      - name: Send message to Telegram
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: |
          curl -X POST \
            -H "Content-Type: application/json" \
            -d '{"chat_id": "'$CHAT_ID'", "text": "${{ github.event.client_payload.message }}"}' \
            https://api.telegram.org/bot$TELEGRAM_TOKEN/sendMessage
