name: Send Telegram Message

on:
  repository_dispatch:
    types:
      - api_hit

jobs:
  send_message:
    runs-on: ubuntu-latest
    steps:
      - name: Send message to Telegram
        run: |
          echo "TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}"
          echo "CHAT_ID: ${{ secrets.CHAT_ID }}"
          response=$(curl -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendMessage" \
          -d "chat_id=${{ secrets.CHAT_ID }}" \
          -d "text=${{ github.event.client_payload.message }}" \
          -s -o response.json -w "%{http_code}")
          echo "HTTP Response Code: $response"
          echo "Response Content:"
          cat response.json
